all: ising_simple_j1 ising_simple_jrandom

ising_simple_j1: ising_simple_j1.cc
	g++ ising_simple_j1.cc -o ising_simple_j1

ising_simple_jrandom: ising_simple_jrandom.cc
	g++ ising_simple_jrandom.cc -o ising_simple_jrandom

clean:
	rm -f ising_simple_j1 ising_simple_jrandom
